# Generated by Django 4.0.5 on 2022-06-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_customer',
        ),
    ]
