# Generated by Django 4.0.5 on 2022-07-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0003_rename_is_admin_customuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='custom-user', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
