# Generated by Django 4.0.5 on 2022-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_customuser_name_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
