# Generated by Django 4.0.6 on 2022-07-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0005_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
