# Generated by Django 4.0.5 on 2022-07-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0006_alter_customuser_password_alter_customuser_username'),
        ('mealapp', '0007_customuser_caterer_customer'),
    ]

    operations = [
    ]
