# Generated by Django 4.0.6 on 2022-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0007_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(to='mealapp.menu'),
        ),
    ]
