# Generated by Django 4.0.5 on 2022-07-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0008_order_city_order_email_order_state_order_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
