# Generated by Django 4.0.6 on 2022-07-07 11:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0008_merge_20220706_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
