# Generated by Django 4.0.5 on 2022-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0009_alter_menu_image_delete_customuser'),
        ('mealapp', '0009_remove_order_city_remove_order_email_and_more'),
    ]

    operations = [
    ]
