# Generated by Django 4.0.6 on 2022-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0009_remove_order_menu_order_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
