# Generated by Django 4.0.6 on 2022-07-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0010_menu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
